GET http://localhost:8080/post/103


###

POST http://localhost:8080/post/add
Content-Type: application/json

{
  "user_id": 12,
  "title": "title echo from request",
  "body": "body echo from request"
}

###
DELETE http://localhost:8080/post/del/103

###
PATCH http://localhost:8080/post/patch/105
Content-Type: application/json

{
  "user_id": 12,
  "title": "update echo title",
  "body": "update echo body from request"
}

###
GET http://localhost:8080/comment/1

###

POST http://localhost:8080/comment/add
Content-Type: application/json

{
  "post_id": 2,
  "name": "new echo comment",
  "email": " echopost@ukr.net",
  "body": "comment echo from Json"
}

###

DELETE http://localhost:8080/comment/del/502

###
PATCH http://localhost:8080/comment/update/499
Content-Type: application/json

{
  "post_id": 1,
  "name": "update echo new comment",
  "email": "update echo post@ukr.net",
  "body": "update echo comment from Json"
}